/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

"use strict";
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => TTRPGSpellCreator
});
module.exports = __toCommonJS(main_exports);
var import_obsidian = require("obsidian");
var TTRPGSpellCreator = class extends import_obsidian.Plugin {
  onload() {
    console.log("TTRPG Spell Creator: Loaded successfully!");
  }
};
//# sourceMappingURL=data:application/json;base64,ewogICJ2ZXJzaW9uIjogMywKICAic291cmNlcyI6IFsic3JjL21haW4udHMiXSwKICAic291cmNlc0NvbnRlbnQiOiBbImltcG9ydCB7IFBsdWdpbn0gZnJvbSAnb2JzaWRpYW4nO1xyXG5cclxuZXhwb3J0IGRlZmF1bHQgY2xhc3MgVFRSUEdTcGVsbENyZWF0b3IgZXh0ZW5kcyBQbHVnaW4ge1xyXG5cdG9ubG9hZCgpOiB2b2lkIHtcclxuXHRcdGNvbnNvbGUubG9nKCdUVFJQRyBTcGVsbCBDcmVhdG9yOiBMb2FkZWQgc3VjY2Vzc2Z1bGx5IScpO1xyXG5cdH1cclxufSJdLAogICJtYXBwaW5ncyI6ICI7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7QUFBQTtBQUFBO0FBQUE7QUFBQTtBQUFBO0FBQUEsc0JBQXNCO0FBRXRCLElBQXFCLG9CQUFyQixjQUErQyx1QkFBTztBQUFBLEVBQ3JELFNBQWU7QUFDZCxZQUFRLElBQUksMkNBQTJDO0FBQUEsRUFDeEQ7QUFDRDsiLAogICJuYW1lcyI6IFtdCn0K
